Update Setting Screen
kantacky/STRAY-IT pull request #33
Opened 2024-05-01 09:13 UTC by inomeu

# Update
設定画面のデザイン変更に伴う実装 (Close #5 )

# Update Details
- 設定画面のメイン画面の変更
- 各画面のフォントの変更
- ライセンス画面とデベロッパー画面の画面遷移の変更
- 各画面のヘッダーの変更

# Confirmed
- [x] ビルドが通ること

# UI Difference
|BEFORE|AFTER|
|:--:|:--:|
|<img width="300" src="https://github.com/kantacky/STRAY-IT/assets/110728083/cd139263-71fd-4198-b0b9-5819726e3dc6"/>|<img width="300" src="https://github.com/kantacky/STRAY-IT/assets/110728083/d1702c61-cf2c-455e-a94b-70a89b2e10da"/>|
|<img width="300" src="https://github.com/kantacky/STRAY-IT/assets/110728083/977bcc74-a5e4-4797-9536-574d25226670"/>|<img width="300" src="https://github.com/kantacky/STRAY-IT/assets/110728083/034a230f-bf84-42b5-bccf-ec793bed5c74"/>|
|<img width="300" src="https://github.com/kantacky/STRAY-IT/assets/110728083/064f826a-9118-40d2-b70c-610c10d18db2"/>|<img width="300" src="https://github.com/kantacky/STRAY-IT/assets/110728083/de4c86f5-853a-4399-983b-067963490ce4"/>|

2024-05-01 14:08 UTC, kantacky requested changes
全体的に、細かい部分 (空白あけるべきところで空いてない、いらない改行がある、空白行で中途半端にインデントされてる) へのツッコミが多いので、気をつけて見てみてね
空白行で中途半端にインデントされてるのは、Cmd+A, Ctrl+Iでコード整形する時に一緒に治るはずだから、一旦やってみてほしいかも

2024-05-01 14:08 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITSetting/DevelopersView.swift
> +                }
![review-suggestion](https://img.shields.io/badge/review-suggestion-blue.svg)
```suggestion
                Button(action: dismiss) {
                    Image(systemName: "chevron.backward")
                }
```

2024-05-01 14:08 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITSetting/LicensesView.swift
> +                }
![review-suggestion](https://img.shields.io/badge/review-suggestion-blue.svg)
```suggestion
                Button(action: dismiss) {
                    Image(systemName: "chevron.backward")
                }
```

2024-05-01 14:08 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITSetting/Localizable.xcstrings
> +      "extractionState" : "stale",
![review-must](https://img.shields.io/badge/review-must-red.svg)
Localizable.xcstringsで`Setting`に`STALE`って書いてあると思うんだけど、もう存在しないやつだから消して大丈夫だよ
消す時は、Englishの方を消すとJapaneseの方も消えるよ
なんのことかわからなければ聞いてね

2024-05-01 14:08 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITSetting/SettingView.swift
> +                    NavigationLink((String(localized: "Developer", bundle: .module))){
![review-nits](https://img.shields.io/badge/review-nits-green.svg)
```suggestion
                    NavigationLink((String(localized: "Developer", bundle: .module))) {
```

2024-05-01 14:08 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITSetting/SettingView.swift
>                          .font(.footnote)
![review-must](https://img.shields.io/badge/review-must-red.svg)
`.strayitFont(.title1)`でフォントを決めてるから、消そう
```suggestion
```

2024-05-01 14:08 UTC, kantacky commented on STRAYITPackage/Sources/STRAYITSetting/SettingView.swift
> +
![review-nits](https://img.shields.io/badge/review-nits-green.svg)
```suggestion
```

2024-05-02 04:58 UTC, inomeu commented on STRAYITPackage/Sources/STRAYITSetting/DevelopersView.swift
> +                ForEach(developers, id: \.self) { developer in
これってlicenceの方もIdentifiableに準拠してる？

2024-05-02 05:01 UTC, inomeu commented on STRAYITPackage/Sources/STRAYITSetting/DevelopersView.swift
> +                ForEach(developers, id: \.self) { developer in
してた！

2024-05-02 05:05 UTC, inomeu commented on STRAYITPackage/Sources/STRAYITSetting/DevelopersView.swift
> +                }
Cannot convert value of type 'DismissAction' to expected argument type '() -> Void'
のエラーでる

2024-05-02 05:28 UTC, kantacky approved these changes
LGTM

2024-05-02 05:29 UTC, merged